### ISSUE TITLE
[ERROR] Can't work.

### ISSUE THREAD

**Issue by 849025143** [BananaPuncher714/Cartographer2#23]
[15:31:49] [Server thread/ERROR]: Could not load 'plugins\[制图师]-Cartographer2-2.15.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/github/bananapuncher714/cartographer/core/Cartographer.loadConfig()V @88: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Exception'
  Current Frame:
    bci: @88
    flags: { }
    locals: { 'io/github/bananapuncher714/cartographer/core/Cartographer', 'io/github/bananapuncher714/cartographer/core/api/configuration/YamlFileConfiguration', 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: bb0a c259 bb02 8759 bb00 7359 b700 742a
    0x0000010: b60a c5b6 03b5 130a c7b6 03ba b603 beb7
    0x0000020: 0288 b609 edb7 0aca 4c2b b60a cbbb 0acd
    0x0000030: 592b 2a13 0acf b605 01b7 0ad2 4d2c 03b6
    0x0000040: 0ad6 572c b60a da57 2cb6 0add 572c 03b6
    0x0000050: 0ae0 57a7 0008 4d2c b60a e12b b60a e54d
    0x0000060: 2abb 097f 59b7 0ae6 b509 562c 130a e8b6
    0x0000070: 0aec b90a ef01 004e 2db9 03f2 0100 9900
    0x0000080: 232d b903 f601 00c0 0091 3a04 2ab4 0956
    0x0000090: b60a f219 04b8 0af5 b90a f802 0057 a7ff
    0x00000a0: da2a 2c13 0afa 1010 b60a feb5 0048 2ab4
    0x00000b0: 0956 2c13 0b00 04b6 0afe b60b 032a b409
    0x00000c0: 562c 130b 0503 b60b 09b6 0b0d 2ab4 0956
    0x00000d0: 2c13 0b0f 04b6 0b09 b60b 122a b409 562c
    0x00000e0: 130b 1404 b60b 09b6 0b17 2ab4 0956 2c13
    0x00000f0: 0b19 08b6 0afe b60b 1c2a b409 562c 130b
    0x0000100: 1e10 14b6 0afe b60b 212a b409 562c 130b
    0x0000110: 2304 b60b 09b6 0b26 2ab4 0956 2c13 0b28
    0x0000120: 04b6 0b09 b60b 2b2a b409 562c 130b 2d04
    0x0000130: b60b 09b6 0b30 2ab4 0956 2c13 0b32 07b6
    0x0000140: 0afe b60b 352a b409 562c 130b 3703 b60b
    0x0000150: 09b6 0b3a bb02 8759 bb00 7359 b700 742a
    0x0000160: b60a c5b6 03b5 1303 b7b6 03ba 2c13 0b3c
    0x0000170: 130b 3eb6 0b40 b603 bab6 03be b702 88b3
    0x0000180: 0b42 bb02 8759 bb00 7359 b700 742a b60a
    0x0000190: c5b6 03b5 1303 b7b6 03ba 2c13 0b44 130b
    0x00001a0: 46b6 0b40 b603 bab6 03be b702 88b3 0b48
    0x00001b0: bb02 8759 bb00 7359 b700 742a b60a c5b6
    0x00001c0: 03b5 1303 b7b6 03ba 2c13 0b4a 130b 4cb6
    0x00001d0: 0b40 b603 bab6 03be b702 88b3 0b4e bb02
    0x00001e0: 8759 bb00 7359 b700 742a b60a c5b6 03b5
    0x00001f0: 1303 b7b6 03ba 2c13 0b50 130b 52b6 0b40
    0x0000200: b603 bab6 03be b702 88b3 0b54 2ab4 0956
    0x0000210: 2c13 0b56 03b6 0b09 b60b 592a b404 bc2c
    0x0000220: 130b 5b13 09ab b60b 40b6 0b5e 2ab4 0956
    0x0000230: 2c13 0b60 100a b60a feb6 0b63 b208 872c
    0x0000240: 130b 6503 b60b 09b6 0b68 b208 872c 130b
    0x0000250: 6a10 32b6 0afe b60b 6db2 0887 2c13 0b6f
    0x0000260: 1014 b60a feb6 0b72 b208 872c 130b 7404
    0x0000270: b60a feb6 0b77 2c13 0b79 b60a ecb9 0aef
    0x0000280: 0100 4e2d b903 f201 0099 004c 2db9 03f6
    0x0000290: 0100 c000 913a 0419 04b8 0b7e 3a05 2ab4
    0x00002a0: 0956 b60b 8119 05b9 0af8 0200 572a 130b
    0x00002b0: 8304 bd03 cf59 0319 0453 b703 d3a7 0015
    0x00002c0: 3a05 2a13 0b85 04bd 03cf 5903 1904 53b7
    0x00002d0: 0b87 a7ff b12b b60b 89a7 0008 4e2d b609
    0x00002e0: c4b1
  Exception Handler Table:
    bci [41, 83] => handler: 86
    bci [41, 83] => handler: 86
    bci [663, 701] => handler: 704
    bci [725, 729] => handler: 732
  Stackmap Table:
    full_frame(@86,{Object[#2],Object[#2754]},{Object[#975]})
    append_frame(@91,Object[#975])
    full_frame(@120,{Object[#2],Object[#2754],Object[#2502],Object[#1006]},{})
    same_frame(@161)
    same_frame_extended(@643)
    full_frame(@704,{Object[#2],Object[#2754],Object[#2502],Object[#1006],Object[#145]},{Object[#2752]})
    append_frame(@722,Object[#975])
    chop_frame(@725,2)
    same_locals_1_stack_item_frame(@732,Object[#215])
    full_frame(@737,{Object[#2],Object[#2754],Object[#2502],Object[#975]},{})

        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[JavaPluginLoader.class:git-CatServer-1.12.2-35187d3]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-35187d3]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-35187d3]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-35187d3]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/github/bananapuncher714/cartographer/core/Cartographer.loadConfig()V @88: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Exception'
  Current Frame:
    bci: @88
    flags: { }
    locals: { 'io/github/bananapuncher714/cartographer/core/Cartographer', 'io/github/bananapuncher714/cartographer/core/api/configuration/YamlFileConfiguration', 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: bb0a c259 bb02 8759 bb00 7359 b700 742a
    0x0000010: b60a c5b6 03b5 130a c7b6 03ba b603 beb7
    0x0000020: 0288 b609 edb7 0aca 4c2b b60a cbbb 0acd
    0x0000030: 592b 2a13 0acf b605 01b7 0ad2 4d2c 03b6
    0x0000040: 0ad6 572c b60a da57 2cb6 0add 572c 03b6
    0x0000050: 0ae0 57a7 0008 4d2c b60a e12b b60a e54d
    0x0000060: 2abb 097f 59b7 0ae6 b509 562c 130a e8b6
    0x0000070: 0aec b90a ef01 004e 2db9 03f2 0100 9900
    0x0000080: 232d b903 f601 00c0 0091 3a04 2ab4 0956
    0x0000090: b60a f219 04b8 0af5 b90a f802 0057 a7ff
    0x00000a0: da2a 2c13 0afa 1010 b60a feb5 0048 2ab4
    0x00000b0: 0956 2c13 0b00 04b6 0afe b60b 032a b409
    0x00000c0: 562c 130b 0503 b60b 09b6 0b0d 2ab4 0956
    0x00000d0: 2c13 0b0f 04b6 0b09 b60b 122a b409 562c
    0x00000e0: 130b 1404 b60b 09b6 0b17 2ab4 0956 2c13
    0x00000f0: 0b19 08b6 0afe b60b 1c2a b409 562c 130b
    0x0000100: 1e10 14b6 0afe b60b 212a b409 562c 130b
    0x0000110: 2304 b60b 09b6 0b26 2ab4 0956 2c13 0b28
    0x0000120: 04b6 0b09 b60b 2b2a b409 562c 130b 2d04
    0x0000130: b60b 09b6 0b30 2ab4 0956 2c13 0b32 07b6
    0x0000140: 0afe b60b 352a b409 562c 130b 3703 b60b
    0x0000150: 09b6 0b3a bb02 8759 bb00 7359 b700 742a
    0x0000160: b60a c5b6 03b5 1303 b7b6 03ba 2c13 0b3c
    0x0000170: 130b 3eb6 0b40 b603 bab6 03be b702 88b3
    0x0000180: 0b42 bb02 8759 bb00 7359 b700 742a b60a
    0x0000190: c5b6 03b5 1303 b7b6 03ba 2c13 0b44 130b
    0x00001a0: 46b6 0b40 b603 bab6 03be b702 88b3 0b48
    0x00001b0: bb02 8759 bb00 7359 b700 742a b60a c5b6
    0x00001c0: 03b5 1303 b7b6 03ba 2c13 0b4a 130b 4cb6
    0x00001d0: 0b40 b603 bab6 03be b702 88b3 0b4e bb02
    0x00001e0: 8759 bb00 7359 b700 742a b60a c5b6 03b5
    0x00001f0: 1303 b7b6 03ba 2c13 0b50 130b 52b6 0b40
    0x0000200: b603 bab6 03be b702 88b3 0b54 2ab4 0956
    0x0000210: 2c13 0b56 03b6 0b09 b60b 592a b404 bc2c
    0x0000220: 130b 5b13 09ab b60b 40b6 0b5e 2ab4 0956
    0x0000230: 2c13 0b60 100a b60a feb6 0b63 b208 872c
    0x0000240: 130b 6503 b60b 09b6 0b68 b208 872c 130b
    0x0000250: 6a10 32b6 0afe b60b 6db2 0887 2c13 0b6f
    0x0000260: 1014 b60a feb6 0b72 b208 872c 130b 7404
    0x0000270: b60a feb6 0b77 2c13 0b79 b60a ecb9 0aef
    0x0000280: 0100 4e2d b903 f201 0099 004c 2db9 03f6
    0x0000290: 0100 c000 913a 0419 04b8 0b7e 3a05 2ab4
    0x00002a0: 0956 b60b 8119 05b9 0af8 0200 572a 130b
    0x00002b0: 8304 bd03 cf59 0319 0453 b703 d3a7 0015
    0x00002c0: 3a05 2a13 0b85 04bd 03cf 5903 1904 53b7
    0x00002d0: 0b87 a7ff b12b b60b 89a7 0008 4e2d b609
    0x00002e0: c4b1
  Exception Handler Table:
    bci [41, 83] => handler: 86
    bci [41, 83] => handler: 86
    bci [663, 701] => handler: 704
    bci [725, 729] => handler: 732
  Stackmap Table:
    full_frame(@86,{Object[#2],Object[#2754]},{Object[#975]})
    append_frame(@91,Object[#975])
    full_frame(@120,{Object[#2],Object[#2754],Object[#2502],Object[#1006]},{})
    same_frame(@161)
    same_frame_extended(@643)
    full_frame(@704,{Object[#2],Object[#2754],Object[#2502],Object[#1006],Object[#145]},{Object[#2752]})
    append_frame(@722,Object[#975])
    chop_frame(@725,2)
    same_locals_1_stack_item_frame(@732,Object[#215])
    full_frame(@737,{Object[#2],Object[#2754],Object[#2502],Object[#975]},{})

        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-35187d3]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-35187d3]
        ... 7 more

**Comment by BananaPuncher714** [comment]
Ok thanks, I'll take a look when I get time.

**Comment by Quik2007** [comment]
[12:51:10 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'Cartographer2-2.15.13.jar' in folder 'plugins/.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/github/bananapuncher714/cartographer/core/Cartographer.saveMapFiles(Ljava/io/File;)V @110: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Exception'
  Current Frame:
    bci: @110
    flags: { }
    locals: { 'io/github/bananapuncher714/cartographer/core/Cartographer', 'java/io/File', 'java/io/File', 'io/github/bananapuncher714/cartographer/core/api/configuration/YamlFileConfiguration', 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: bb00 7e59 bb00 8059 b700 812b b600 8913
    0000010: 0312 b600 8eb6 0092 b700 944d 2a13 049c
    0000020: b602 3e2c 03b8 0244 bb03 1059 2cb6 0316
    0000030: b703 194e 2db6 031a bb03 1c59 2d2a 1304
    0000040: 9cb6 023e b703 1f3a 0419 0403 b603 2357
    0000050: 1904 b603 2757 1904 b603 2a57 1904 03b6
    0000060: 032d 572d b603 e4a7 000a 3a04 1904 b603
    0000070: 30b1                                   
  Exception Handler Table:
    bci [52, 103] => handler: 106
    bci [52, 103] => handler: 106
  Stackmap Table:
    full_frame(@106,{Object[#2],Object[#126],Object[#126],Object[#784]},{Object[#251]})
    append_frame(@113,Object[#251])

	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:39) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:577) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	at java.base/java.lang.Thread.run(Thread.java:1447) ~[?:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/github/bananapuncher714/cartographer/core/Cartographer.saveMapFiles(Ljava/io/File;)V @110: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Exception'
  Current Frame:
    bci: @110
    flags: { }
    locals: { 'io/github/bananapuncher714/cartographer/core/Cartographer', 'java/io/File', 'java/io/File', 'io/github/bananapuncher714/cartographer/core/api/configuration/YamlFileConfiguration', 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: bb00 7e59 bb00 8059 b700 812b b600 8913
    0000010: 0312 b600 8eb6 0092 b700 944d 2a13 049c
    0000020: b602 3e2c 03b8 0244 bb03 1059 2cb6 0316
    0000030: b703 194e 2db6 031a bb03 1c59 2d2a 1304
    0000040: 9cb6 023e b703 1f3a 0419 0403 b603 2357
    0000050: 1904 b603 2757 1904 b603 2a57 1904 03b6
    0000060: 032d 572d b603 e4a7 000a 3a04 1904 b603
    0000070: 30b1                                   
  Exception Handler Table:
    bci [52, 103] => handler: 106
    bci [52, 103] => handler: 106
  Stackmap Table:
    full_frame(@106,{Object[#2],Object[#126],Object[#126],Object[#784]},{Object[#251]})
    append_frame(@113,Object[#251])

	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:543) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[purpur-1.21.4.jar:1.21.4-2408-5d1df70]
	... 9 more

**Comment by 737** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到，尽快会给您回复。谢谢!
