### ISSUE TITLE
[20:57:30 ERROR]: null after load FactionsAddon-1.0.1.jar

### ISSUE THREAD

**Issue by DENPOY** [BananaPuncher714/Cartographer2#25]
[20:57:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cartographer' in plugin Cartographer2 v2.15.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/iface/RelationParticipator
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.module.ModuleClassLoader.<init>(ModuleClassLoader.java:48) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.module.ModuleLoader.load(ModuleLoader.java:80) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.ModuleManager.loadModule(ModuleManager.java:70) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.command.CommandModule.load(CommandModule.java:141) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.api.command.CommandOption.execute(CommandOption.java:23) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.api.command.CommandResult.execute(CommandResult.java:36) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.api.command.SubCommand.onCommand(SubCommand.java:205) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]
        ... 19 more
Caused by: java.lang.ClassNotFoundException:
 com.massivecraft.factions.iface.RelationParticipator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.module.ModuleClassLoader.findClass(ModuleClassLoader.java:131) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.module.ModuleClassLoader.findClass(ModuleClassLoader.java:66) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.module.ModuleClassLoader.<init>(ModuleClassLoader.java:48) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.module.ModuleLoader.load(ModuleLoader.java:80) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.ModuleManager.loadModule(ModuleManager.java:70) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.command.CommandModule.load(CommandModule.java:141) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.api.command.CommandOption.execute(CommandOption.java:23) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.api.command.CommandResult.execute(CommandResult.java:36) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.api.command.SubCommand.onCommand(SubCommand.java:205) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]

**Comment by BananaPuncher714** [comment]
This plugin supports FactionsUUID, not MassiveCraft factions.
