### ISSUE TITLE
VanillaPlus-1.0.4.jar

### ISSUE THREAD

**Issue by Bibo89** [BananaPuncher714/Cartographer2#28]
[Cartographer2] Task #41820 for Cartographer2 v2.15.6 generated an exception
java.lang.NullPointerException: Cannot invoke "io.github.bananapuncher714.cartographer.module.vanilla.providers.CursorProviderPlayer.getFor(org.bukkit.entity.Player, io.github.bananapuncher714.cartographer.core.renderer.PlayerSetting)" because "this.playerProvider" is null
        at io.github.bananapuncher714.cartographer.module.vanilla.VanillaWorldCursorProvider.getCursors(VanillaWorldCursorProvider.java:71) ~[?:?]
        at io.github.bananapuncher714.cartographer.core.map.Minimap.getCursorsFor(Minimap.java:316) ~[Cartographer2-2.15.6.jar:?]
        at io.github.bananapuncher714.cartographer.core.renderer.CartographerRenderer.update(CartographerRenderer.java:216) ~[Cartographer2-2.15.6.jar:?]
        at io.github.bananapuncher714.cartographer.core.renderer.CartographerRenderer.tickRender(CartographerRenderer.java:550) ~[Cartographer2-2.15.6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-445]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-445]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-445]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>

**Comment by BananaPuncher714** [comment]
Does this error occur consistently, and do you have steps to reproduce?

**Comment by Bibo89** [comment]
a

**Comment by Bibo89** [comment]
I just activated the vanilla plus module

**Comment by BananaPuncher714** [comment]
Does your vanilla plus config contain a `players` section? Try removing the config file and turning the module back on. If you do not want players to be displayed, you can set the `players.enabled` option to `false` instead of deleting it.
