### ISSUE TITLE
event exception with latest Spigot 1.15.2 build

### ISSUE THREAD

**Issue by fichdlmaa** [BananaPuncher714/Cartographer2#3]
REF:
- Cartographer2, Version 2.12.16
- latest Spigot 1.15.2 build (2020-02-22 after 15:00 p.m. UTC)
- Java2 Vers 11 on Debian 10 Buster 

Hello BananaPuncher, -- all ok with Cartographer2 on 1.14.4, but -- 
on freshly generated 1.15.2 I get the following error(s) on server console:

....
[19:10:37] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[19:10:37] [Server thread/INFO]: [Cartographer2] Enabling modules...
[19:10:37] [Server thread/INFO]: [Cartographer2] [ModuleManager] Enabling WayPoints v1.3 by BrainRTP
[19:10:37] [Server thread/INFO]: [Cartographer2] Loading minimaps and data...
[19:10:37] [Server thread/INFO]: [Cartographer2] [MapManager] Loading minimap 'Test'
[19:10:37] [Server thread/ERROR]: Could not pass event ServerLoadEvent to Cartographer2 v2.12.16
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:541) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:528) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:458) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at io.github.bananapuncher714.cartographer.core.MinimapManager.convert(MinimapManager.java:119) ~[?:?]
	at io.github.bananapuncher714.cartographer.core.Cartographer.loadData(Cartographer.java:262) ~[?:?]
	at io.github.bananapuncher714.cartographer.core.Cartographer.loadAfter(Cartographer.java:235) ~[?:?]
	at io.github.bananapuncher714.cartographer.core.Cartographer.onServerLoad(Cartographer.java:173) ~[?:?]
	at io.github.bananapuncher714.cartographer.core.CartographerListener.onServerLoadEvent(CartographerListener.java:17) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-fba9f48]
	... 7 more
[19:10:37] [Server thread/INFO]: Done (27.995s)! For help, type "help"
[19:10:37] [Server thread/INFO]: [AsyncWorldEdit] Loading plugins...
...

I hope you find *the* solution for this issue :-D

Greets from 

(Minecraft) FichdlMaa

**Comment by BananaPuncher714** [comment]
Sorry for the late reply, I'll take a look when I have time.

**Comment by BananaPuncher714** [comment]
Please use the latest build of Cartographer and re-open if this issue still persists.
