### ISSUE TITLE
1.20.6 issues

### ISSUE THREAD

**Issue by JuergenUniVie** [BananaPuncher714/Cartographer2#30]
[11:43:31] [Server thread/ERROR]: Error occurred while enabling Cartographer2 v2.15.10 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at Cartographer2-2.15.10.jar/io.github.bananapuncher714.cartographer.core.Cartographer.onEnable(Cartographer.java:136) ~[Cartographer2-2.15.10.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at Cartographer2-2.15.10.jar/io.github.bananapuncher714.cartographer.core.util.ReflectionUtil.<clinit>(ReflectionUtil.java:16) ~[Cartographer2-2.15.10.jar:?]
	... 13 more
[11:43:31] [Server thread/INFO]: [Cartographer2] Disabling Cartographer2 v2.15.10
[11:43:31] [Server thread/INFO]: [Cartographer2] Disabling modules...
[11:43:31] [Server thread/INFO]: [Cartographer2] Saving map data. This may take a while...
[11:43:31] [Server thread/INFO]: [Cartographer2] Saving map data complete!
[11:43:31] [Server thread/INFO]: [Cartographer2] Saving player data...
[11:43:31] [Server thread/INFO]: [Cartographer2] Saving player data complete!

**Comment by BananaPuncher714** [comment]
Thanks, I'll update it when I have the time.
