### ISSUE TITLE
[Bug]Plugin can't load at server starting

### ISSUE THREAD

**Issue by Tiplish** [BananaPuncher714/Cartographer2#4]
Hi,

When i try to load cartographer2, i get this error : 

```
[10:21:07] [Server thread/INFO]: [Cartographer2] Enabling Cartographer2 v2.12.16
[10:21:07] [Server thread/INFO]: Captured 207 colors!
[10:21:09] [Server thread/INFO]: Initial lookup table initialized in 1858.373553 ms
[10:21:09] [Server thread/ERROR]: Error occurred while enabling Cartographer2 v2.12.16 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at io.github.bananapuncher714.cartographer.core.Cartographer.onEnable(Cartographer.java:114) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[paperspigot.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[paperspigot.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[paperspigot.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[paperspigot.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Unable to find method null ([class net.minecraft.server.v1_15_R1.ServerConnection]).
	at io.github.bananapuncher714.cartographer.tinyprotocol.Reflection.getTypedMethod(Reflection.java:242) ~[?:?]
	at io.github.bananapuncher714.cartographer.tinyprotocol.Reflection.getMethod(Reflection.java:203) ~[?:?]
	at io.github.bananapuncher714.cartographer.tinyprotocol.Reflection.getTypedMethod(Reflection.java:240) ~[?:?]
	at io.github.bananapuncher714.cartographer.tinyprotocol.TinyProtocol.<clinit>(TinyProtocol.java:59) ~[?:?]
	... 10 more
[10:21:09] [Server thread/INFO]: [Cartographer2] Disabling Cartographer2 v2.12.16
[10:21:09] [Server thread/INFO]: [Cartographer2] Disabling modules...
[10:21:09] [Server thread/ERROR]: Error occurred while disabling Cartographer2 v2.12.16 (Is it up to date?)
java.lang.NullPointerException: null
	at io.github.bananapuncher714.cartographer.core.Cartographer.onDisable(Cartographer.java:150) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:372) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:468) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:341) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[paperspigot.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[paperspigot.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[paperspigot.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[paperspigot.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[paperspigot.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Tests :** 
- I've try to remove the config but it doesn't work.

- Another test that we have done, is to delete all files of cartographer2 but the error still happend at the start of the server.

- On paper #133, we hadn't this behaviour.

**Versions used :** 
Cartographer2 (Cartographer2 v2.12.16)
Waypoints (1.5)
Paper (#143)

**Comment by BananaPuncher714** [comment]
Which version of Java are you using?

**Comment by Hiobi** [comment]
Hi @BananaPuncher714 

We using openjdk-11 under our own docker image : 
https://hub.docker.com/repository/docker/nefald/papermc

Based on `openjdk:11` image.

* I updated to Paper #146, the error still occurred.
* I runned the server just with Cartographer2, the error still occurred.

### Details
* Openjdk-11
* Cartographer2 (Cartographer2 v2.12.16)
* Waypoints 1.5
* Paper 1.15.2 #146 

Thanks !

**Comment by BananaPuncher714** [comment]
This appears to be an issue with compiling Paper on Java 11 and TinyProtocol being unable to locate the correct classes. I'll see what I can do.

**Comment by BananaPuncher714** [comment]
The newest version (2.12.17) should fix these problems. Re-open this issue if the errors still persist.

**Comment by Hiobi** [comment]
Thanks @BananaPuncher714  ! :)
