### ISSUE TITLE
small error bug

### ISSUE THREAD

**Issue by pluttotv** [BananaPuncher714/Cartographer2#6]
hey , i got this method on that going into gm disable all custom items
found a small bug that if u hold a map then go creative it drop this error:

[Cartographer2] Task #3408 for Cartographer2 v2.12.17 generated an exception
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaMap.getMapId(CraftMetaMap.java:146) ~[patched_1.15.2.jar:git-Paper-378]
	at io.github.bananapuncher714.cartographer.core.internal.Util_1_13.getMapViewFrom(Util_1_13.java:33) ~[?:?]
	at io.github.bananapuncher714.cartographer.core.renderer.CartographerRenderer.tickRender(CartographerRenderer.java:397) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-378]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-378]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-378]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

i guess u just need to thro a safe failcheck to see ur not geting null map as result of the map changing to normal one.

**Comment by BananaPuncher714** [comment]
I'm going to close this issue since it should have been fixed as of now. If it is still happening, feel free to reopen.
