### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by istarengwa** [BananaPuncher714/Cartographer2#8]
Hello, the plugin worked extremely well before the installation of the modules, once the modules were put it did not work anymore, I had to delete the complete folder to try to make it work, and it refuses to install.

Log : 
[14:32:00] [Server thread/INFO]: [Cartographer2] Loading config...
[14:32:00] [Server thread/INFO]: [Cartographer2] Added 'ANVIL' as a blacklisted inventory
[14:32:00] [Server thread/INFO]: [Cartographer2] Added 'WORKBENCH' as a blacklisted inventory
[14:32:00] [Server thread/INFO]: [Cartographer2] Added 'CARTOGRAPHY' as a blacklisted inventory
[14:32:00] [Server thread/INFO]: [Cartographer2] Loading images...
[14:32:00] [Server thread/INFO]: [Cartographer2] Overlay detected!
[14:32:00] [Server thread/ERROR]: Error occurred while enabling Cartographer2 v2.14.4 (Is it up to date?)
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_232]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_232]
	at java.awt.Image.getScaledInstance(Image.java:178) ~[?:1.8.0_232]
	at io.github.bananapuncher714.cartographer.core.api.SimpleImage.<init>(SimpleImage.java:115) ~[?:?]
	at io.github.bananapuncher714.cartographer.core.Cartographer.loadImages(Cartographer.java:420) ~[?:?]
	at io.github.bananapuncher714.cartographer.core.Cartographer.load(Cartographer.java:259) ~[?:?]
	at io.github.bananapuncher714.cartographer.core.Cartographer.onEnable(Cartographer.java:170) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Purpur-821]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Purpur-821]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Purpur-821]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Purpur-821]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Purpur-821]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.4.jar:git-Purpur-821]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:249) ~[patched_1.16.4.jar:git-Purpur-821]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.4.jar:git-Purpur-821]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Purpur-821]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[14:32:00] [Server thread/INFO]: [Cartographer2] Disabling Cartographer2 v2.14.4

Server version : purpurclip-821 (Mc 1.16.4)
Plugin version : 2.14.4

**Comment by BananaPuncher714** [comment]
You need to run the server with the flag `-Djavax.accessibility.assistive_technologies=" "`
